name: "Yro Hassio Beem Box v0.0.1b"
description: "Hassio Beem Box bridge for Home Assistant"
url: "https://github.com/mak-gitdev/HA_enoceanmqtt-addon"
version: "0.0.1b"
slug: "yro_hassio_beem"
stage: "experimental"
init: false
uart: false
hassio_api: false
homeassistant_api: true
startup: "application"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_file: "/config/yro_hassio_beem.log"
  debug: false
schema:
  log_file: "str?"
  debug: "bool?"
